[book]
authors = ["Trail of Bits"]
language = "en"
multilingual = false
src = "."
title = "Building Secure Contracts"
description = "Follow our guidelines and best practices to write secure smart contracts."

[output.html]
git-repository-url = "https://github.com/crytic/building-secure-contracts"
edit-url-template = "https://github.com/crytic/building-secure-contracts/edit/master/{path}"
default-theme = "ayu"
cname = "crytic.github.io/building-secure-contracts"
no-section-label = true

[output.html.fold]
enable = true
level = 1